package com.parcial2.modelo;
// Generated May 16, 2016 7:18:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Application generated by hbm2java
 */
public class Application  implements java.io.Serializable {


     private Integer idapplication;
     private Category category;
     private String developedBy;
     private Date devDate;
     private String release;
     private boolean released;
     private int downloads;

    public Application() {
    }

    public Application(Category category, String developedBy, Date devDate, String release, boolean released, int downloads) {
       this.category = category;
       this.developedBy = developedBy;
       this.devDate = devDate;
       this.release = release;
       this.released = released;
       this.downloads = downloads;
    }
   
    public Integer getIdapplication() {
        return this.idapplication;
    }
    
    public void setIdapplication(Integer idapplication) {
        this.idapplication = idapplication;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getDevelopedBy() {
        return this.developedBy;
    }
    
    public void setDevelopedBy(String developedBy) {
        this.developedBy = developedBy;
    }
    public Date getDevDate() {
        return this.devDate;
    }
    
    public void setDevDate(Date devDate) {
        this.devDate = devDate;
    }
    public String getRelease() {
        return this.release;
    }
    
    public void setRelease(String release) {
        this.release = release;
    }
    public boolean isReleased() {
        return this.released;
    }
    
    public void setReleased(boolean released) {
        this.released = released;
    }
    public int getDownloads() {
        return this.downloads;
    }
    
    public void setDownloads(int downloads) {
        this.downloads = downloads;
    }




}


