package com.parcial2.modelo;
// Generated May 16, 2016 7:18:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer idcategory;
     private String name;
     private Set applications = new HashSet(0);

    public Category() {
    }

	
    public Category(String name) {
        this.name = name;
    }
    public Category(String name, Set applications) {
       this.name = name;
       this.applications = applications;
    }
   
    public Integer getIdcategory() {
        return this.idcategory;
    }
    
    public void setIdcategory(Integer idcategory) {
        this.idcategory = idcategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getApplications() {
        return this.applications;
    }
    
    public void setApplications(Set applications) {
        this.applications = applications;
    }




}


