package com.parcial2.modelo;
// Generated May 16, 2016 7:18:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Folder generated by hbm2java
 */
public class Folder  implements java.io.Serializable {


     private int idfolder;
     private String folderName;
     private Set messages = new HashSet(0);

    public Folder() {
    }

	
    public Folder(int idfolder, String folderName) {
        this.idfolder = idfolder;
        this.folderName = folderName;
    }
    public Folder(int idfolder, String folderName, Set messages) {
       this.idfolder = idfolder;
       this.folderName = folderName;
       this.messages = messages;
    }
   
    public int getIdfolder() {
        return this.idfolder;
    }
    
    public void setIdfolder(int idfolder) {
        this.idfolder = idfolder;
    }
    public String getFolderName() {
        return this.folderName;
    }
    
    public void setFolderName(String folderName) {
        this.folderName = folderName;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }




}


