package com.parcial2.modelo;
// Generated May 16, 2016 7:18:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private Integer idTelefono;
     private Marca marca;
     private String modelo;
     private Date fechaCompra;
     private String ubicacion;
     private int extension;
     private boolean activo;
     private String descEstado;

    public Telefono() {
    }

    public Telefono(Marca marca, String modelo, Date fechaCompra, String ubicacion, int extension, boolean activo) {
       this.marca = marca;
       this.modelo = modelo;
       this.fechaCompra = fechaCompra;
       this.ubicacion = ubicacion;
       this.extension = extension;
       this.activo = activo;
    }
   
    public Integer getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(Integer idTelefono) {
        this.idTelefono = idTelefono;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public int getExtension() {
        return this.extension;
    }
    
    public void setExtension(int extension) {
        this.extension = extension;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    public String getDescEstado() {
        return descEstado;
    }

    public void setDescEstado(String descEstado) {
        this.descEstado = descEstado;
    }




}


