package com.parcial2.modelo;
// Generated May 16, 2016 7:18:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private Integer idVehiculo;
     private Modelo modelo;
     private String placa;
     private Date fechaVenta;
     private String propietario;
     private boolean garantia;

    public Vehiculo() {
    }

    public Vehiculo(Modelo modelo, String placa, Date fechaVenta, String propietario, boolean garantia) {
       this.modelo = modelo;
       this.placa = placa;
       this.fechaVenta = fechaVenta;
       this.propietario = propietario;
       this.garantia = garantia;
    }
   
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(String propietario) {
        this.propietario = propietario;
    }
    public boolean isGarantia() {
        return this.garantia;
    }
    
    public void setGarantia(boolean garantia) {
        this.garantia = garantia;
    }




}


